In [1]:
import pandas as pd    ##data handling
import numpy          ##numerical python  in mathematical calc
from sklearn import svm      ## proving us regarding algorithm
from sklearn.linear_model import LogisticRegression

In [2]:
data = pd.read_csv('data_arrhythmia.csv')

In [5]:
data.head()

,Age,Sex,Height,Weight,qrs_duration,p-r_interval,q-t_interval,t_interval,p_interval,qrs,...,KY,KZ,LA,LB,LC,LD,LE,LF,LG,diagnosis
0,75,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0,0.9,2.9,23.3,49.4,8
1,56,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0,0.2,2.1,20.4,38.8,6
2,54,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0,0.3,3.4,12.3,49.0,10
3,55,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0,0.4,2.6,34.6,61.6,1
4,75,0,190,80,88,181,360,177,103,-16,...,0.0,13.1,-3.6,0.0,0,-0.1,3.9,25.4,62.8,7

In [33]:
data["diagnosis"].unique()

array([ 8,  6, 10,  1,  7, 14,  3, 16,  2,  4,  5,  9, 15], dtype=int64)

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1356 entries, 0 to 1355
Columns: 280 entries, Age to diagnosis
dtypes: float64(121), int64(159)
memory usage: 2.9 MB

In [35]:
data.describe()

,Age,Sex,Height,Weight,qrs_duration,p-r_interval,q-t_interval,t_interval,p_interval,qrs,...,KY,KZ,LA,LB,LC,LD,LE,LF,LG,diagnosis
count,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,...,1356.000000,1356.000000,1356.000000,1356.000000,1356.0,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000
mean,46.471239,0.550885,166.188053,68.170354,88.920354,155.152655,367.207965,169.949115,90.004425,33.676991,...,-0.278982,9.048009,-1.457301,0.003982,0.0,0.514823,1.222345,19.326106,29.473230,3.880531
std,16.454474,0.497587,37.142898,16.578554,15.353051,44.809176,33.360774,35.606765,25.807576,45.397893,...,0.548471,3.470298,2.000951,0.050081,0.0,0.347274,1.424999,13.493952,18.480273,4.403843
min,0.000000,0.000000,105.000000,6.000000,55.000000,0.000000,232.000000,108.000000,0.000000,-172.000000,...,-4.100000,0.000000,-28.600000,0.000000,0.0,-0.800000,-6.000000,-44.200000,-38.600000,1.000000
25%,36.000000,0.000000,160.000000,59.000000,80.000000,142.000000,350.000000,148.000000,79.000000,3.750000,...,-0.425000,6.600000,-2.100000,0.000000,0.0,0.400000,0.500000,11.450000,17.550000,1.000000
50%,47.000000,1.000000,164.000000,68.000000,86.000000,157.000000,367.000000,162.000000,91.000000,40.000000,...,0.000000,8.800000,-1.100000,0.000000,0.0,0.500000,1.350000,18.100000,27.900000,1.000000
75%,58.000000,1.000000,170.000000,79.000000,94.000000,175.000000,384.000000,179.000000,102.000000,66.000000,...,0.000000,11.200000,0.000000,0.000000,0.0,0.700000,2.100000,25.825000,41.125000,6.000000
max,83.000000,1.000000,780.000000,176.000000,188.000000,524.000000,509.000000,381.000000,205.000000,169.000000,...,0.000000,23.600000,0.000000,0.800000,0.0,2.400000,6.000000,88.800000,115.900000,16.000000

# PRE PROCESSING DATA (Removing Missing & NaN values)

In [36]:
data = data.fillna(data.mean())

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1356 entries, 0 to 1355
Columns: 280 entries, Age to diagnosis
dtypes: float64(121), int64(159)
memory usage: 2.9 MB

In [38]:
data.isnull().sum()

Age             0
Sex             0
Height          0
Weight          0
qrs_duration    0
               ..
LD              0
LE              0
LF              0
LG              0
diagnosis       0
Length: 280, dtype: int64

In [39]:
X = data.iloc[:,:-1]
X=numpy.array(X)
X=X.astype(numpy.float)

y = data.iloc[:,-1]
y=numpy.array(y)
y=y.astype(numpy.int)

C:\Users\Romes\AppData\Local\Temp\ipykernel_24948\3665311844.py:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X=X.astype(numpy.float)
C:\Users\Romes\AppData\Local\Temp\ipykernel_24948\3665311844.py:13: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y=y.astype(numpy.int)

# applying random forests to get pricipal attributes

In [40]:
#applying random forests to get pricipal attributes
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier()
model.fit(X, y.ravel())
#print(model.feature_importances_)

numpy.savetxt("randforrests.csv", model.feature_importances_, fmt='%s', delimiter=",")

#selecting features 
c=0;
important_features=numpy.zeros((278),dtype=numpy.float)
important_features_index=numpy.zeros((278),dtype=numpy.int)

for i in range (0,278):
    if((model.feature_importances_[i]*1000)>=4.5):
        important_features[c]=model.feature_importances_[i]
        important_features_index[c]=i
        c=c+1

print(important_features)
print(important_features_index)
print("The no of features =",c)

#features are reduced  from 278

numpy.savetxt("import_features_index_after_random_forrests.csv",important_features_index, fmt='%s', delimiter=",")

#new matrix compirising of reduced features
newX=numpy.zeros((1356 ,c),dtype=numpy.float)
for i in range (0,1356 ):
    for j in range (0,c):
        newX[i][j]=X[i][important_features_index[j]]


print(newX)

numpy.savetxt("reduced_features.csv",newX, fmt='%s', delimiter=",")

C:\Users\Romes\AppData\Local\Temp\ipykernel_24948\340371113.py:11: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  important_features=numpy.zeros((278),dtype=numpy.float)
C:\Users\Romes\AppData\Local\Temp\ipykernel_24948\340371113.py:12: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  important_features_index=numpy.zeros((278),dtype=numpy.int)

[0.00570396 0.00533375 0.00483138 0.00530472 0.01142806 0.00590752
 0.00907934 0.00821707 0.00552227 0.00779361 0.00531523 0.019273
 0.0053935  0.00701432 0.00466226 0.0053407  0.00537992 0.0055874
 0.00451935 0.00573376 0.00694453 0.00548211 0.00588866 0.00530099
 0.00786157 0.00475915 0.00576168 0.00494643 0.00623445 0.02662707
 0.02085607 0.00761409 0.00583745 0.00886858 0.01109203 0.00687606
 0.00883563 0.00708852 0.01001266 0.0070761  0.00521934 0.00456473
 0.00539671 0.00543597 0.00515696 0.00519131 0.00658987 0.00530443
 0.00605442 0.00622483 0.00458201 0.0085163  0.00641543 0.00534977
 0.00759622 0.0051552  0.00545515 0.00869137 0.00627055 0.00525489
 0.00670519 0.00548389 0.0077213  0.0062192  0.01337276 0.00708229
 0.00513658 0.00634202 0.00472131 0.00663551 0.0047679  0.00465942
 0.00462021 0.00572559 0.00580079 0.00587901 0.01404642 0.00639827
 0.00459969 0.00602999 0.0048987  0.00741032 0.00604294 0.00939313
 0.00518811 0.00680071 0.00618716 0.00472998 0.00630194 0.00550215
 0.0046512  0.00616647 0.00663858 0.00620124 0.00574696 0.0071093
 0.00585958 0.00468457 0.00957223 0.00471546 0.00606058 0.00948809
 0.00475385 0.0050056  0.01084066 0.00548954 0.00714096 0.00490732
 0.01344939 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.        ]
[  0   1   2   3   4   5   6   7   8  10  12  14  16  17  27  28  29  39
  44  51  52  56  64  68  75  77  80  88  89  90  92  99 100 101 102 104
 111 112 113 116 123 124 125 128 136 140 148 152 159 162 165 166 168 169
 170 172 175 176 178 179 180 186 189 191 196 198 199 206 208 210 211 212
 215 216 219 221 223 225 226 227 228 229 232 233 235 236 237 238 239 240
 241 242 246 247 248 249 251 255 256 257 258 259 261 265 266 268 269 275
 276   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0]
The no of features = 109
[[ 75.    0.  190.  ...  -0.3   0.9   2.9]
 [ 56.    1.  165.  ...  -0.5   0.2   2.1]
 [ 54.    0.  172.  ...   0.9   0.3   3.4]
 ...
 [ 36.    0.  166.  ...   1.2   1.5   1. ]
 [ 32.    1.  155.  ...   0.2   0.5   2.4]
 [ 78.    1.  160.  ...  -0.3   0.5   1.6]]

C:\Users\Romes\AppData\Local\Temp\ipykernel_24948\340371113.py:29: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  newX=numpy.zeros((1356 ,c),dtype=numpy.float)

In [41]:
x = pd.read_csv('reduced_features.csv')

In [42]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(x,y[:-1],test_size=0.2,random_state=100)